# Production context: all deploys from the Production branch 
# set in your site’s Branches settings in the UI will inherit 
# these settings. You can define environment variables 
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository. 
[context.production]
  environment = { NODE_VERSION = "14.19" }
[build.environment]
  NPM_FLAGS="--prefix=/dev/null"
[build]
  publish = "dist"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"